--- Makefile	2022-04-29 19:36:04.535623088 +0000
+++ Makefile	2022-04-29 19:36:56.107575826 +0000
@@ -1,11 +1,22 @@
+all: main
+
 CC = clang
-override CFLAGS += -g -Wno-everything
+override CFLAGS += -g -Wno-everything -pthread -lm
 
 SRCS = $(shell find . -name '.ccls-cache' -type d -prune -o -type f -name '*.c' -print)
-OBJS = $(patsubst %.c, %.o, $(SRCS))
+OBJS = $(SRCS:.c=.o)
+DEPS = $(SRCS:.c=.d)
+
+%.d: %.c
+	@set -e; rm -f $@; \
+	$(CC) -MM $(CFLAGS) $< > $@.$$$$; \
+	sed 's,\($*\)\.o[ :]*,\1.o $@ : ,g' < $@.$$$$ > $@; \
+	rm -f $@.$$$$
+
+include $(DEPS)
 
 main: $(OBJS)
 	$(CC) $(CFLAGS) $(OBJS) -o main
 
 clean:
-	rm -f $(OBJS) main+	rm -f $(OBJS) $(DEPS) main